#!/usr/bin/env python3
"""
HP3458A Diagnostic Utility

Python 3.9
PyVISA
PyQt5

xDevs.com testing
"""

import sys
import datetime
import time

import json
import os
import vxi11
import pyvisa

from PyQt5.QtWidgets import (
    QApplication,
    QMainWindow,
    QWidget,
    QPushButton,
    QPlainTextEdit,
    QLabel,
    QComboBox,
    QHBoxLayout,
    QVBoxLayout,
    QMessageBox,
    QFileDialog,
    QLineEdit
)

from PyQt5.QtCore import Qt, QTimer
from PyQt5.QtGui import QPixmap
from PyQt5.QtGui import QFont
from PyQt5.QtWidgets import QWidget, QDialog, QTextEdit, QLabel, QFrame, QHBoxLayout, QMessageBox

import traceback

HELP_TEXT = " \
 Rev 0.2 | Diagnostics for checking HP/Agilent/Keysight 3458A | 27.JUN.2026 (C)  \r \
 ==============================================================================  \r \
 Supported communication backends : pyVISA or python-vxi11 LXI/VXI               \r \
   Suggested use case:                                                           \r \
 1. Note down your 3458A serial number and GPIB address, connect GPIB            \r \
 2. Configure backend, VISA or LXI/VXI(e.g. using E5810A gateway)                \r \
 3. Enter correct GPIB address to the desired DMM                                \r \
 4. Click connect button, should go green if all is ok                           \r \
 5. 3458A responds only to ID? command, other instruments use *IDN?              \r \
 6. Use buttons ERRSTR? multiple times to read back current fault log            \r \
 7. DUMP CAL VALUES button reads all calibration constants from 3458             \r \
 8. ACAL buttons trigger artifact adjustment function. Use ERRSTR? after         \r \
 9. RUN SELF-TEST button triggers self test. Use ERRSTR? to check fails          \r \
10. Set ACV sync configs 3458A to syncronous mode, helps check A2 PCBA           \r \
11. Read CALSTR? helps to dump user note sometimes stored in CALROM              \r \
                                                                                 \r \
  Program saves text log file with all communication into autogenerated logfile  \r \
  Backend settings and GPIB address, serial number are automatically saved too   \r \
  Comments and feedback welcome via https://bbs.xdevs.com or team@xdevs.com      \r \
   Glory for Ukraine! Support our defenders and help us fight for our home!      \r \
"

##########################################################################
# VISA WRAPPER
##########################################################################

class HP3458A:

    def __init__(self, logger_callback=None):

        self.rm = None
        self.inst = None
        
        self.vxi = None
        self.backend = None  # "visa" or "vxi11"
        
        self.log = logger_callback

    def set_logger(self, cb):
        self.log = cb

    def _log(self, msg):
        if self.log:
            self.log(msg)

    #def open(self, resource):
    #
    #    self.rm = pyvisa.ResourceManager()
    #    self.inst = self.rm.open_resource(resource)
    #
    #    self.inst.timeout = 10000
    #    self.inst.read_termination = "\n"
    #    self.inst.write_termination = "\n"
    #
    #    self._log(f"VISA OPEN {resource}")
    # ---------------------------------------------------------
    # VISA CONNECT
    # ---------------------------------------------------------
    def open_visa(self, resource):

        self.backend = "visa"

        self.rm = pyvisa.ResourceManager()
        self.inst = self.rm.open_resource(resource)

        self.inst.timeout = 10000
        self.inst.read_termination = "\n"
        self.inst.write_termination = "\n"

        self._log(f"VISA OPEN {resource}")

    # ---------------------------------------------------------
    # VXI-11 CONNECT (E5810A)
    # ---------------------------------------------------------
    def open_vxi11(self, ip, gpib_addr):

        self.backend = "vxi11"

        # HP 3458A default node via E5810A
        resource = f"gpib0,{gpib_addr}"
        print (ip, resource)
        self.vxi = vxi11.Instrument(ip, resource)
        self.vxi.timeout = 2
        self.vxi.clear()
        print ("Clearing interface")
        self._log(f"VXI11 OPEN {ip} {resource}")

    def close(self):

        if self.backend == "visa":

            if self.inst:
                self.inst.close()
                self.inst = None

            if self.rm:
                self.rm.close()
                self.rm = None

        elif self.backend == "vxi11":

            if self.vxi:
                self.vxi.close()
                self.vxi = None

        self._log("DEVICE CLOSED")
        self.backend = None
        
    # ---------------------------------------------------------
    def write(self, cmd):

        self._log(f"TX  {cmd}")

        if self.backend == "visa":
            self.inst.write(cmd)

        elif self.backend == "vxi11":
            self.vxi.clear()
            self.vxi.write(cmd)
    
    # ---------------------------------------------------------
    def read(self):

        self._log(f"RX  ")

        if self.backend == "visa":
            self.inst.read()

        elif self.backend == "vxi11":
            self.vxi.read()
            
    # ---------------------------------------------------------
    def query(self, cmd):

        self._log(f"TX  {cmd}")

        if self.backend == "visa":
            resp = self.inst.query(cmd)

        elif self.backend == "vxi11":
            self.vxi.write(cmd)
            time.sleep(0.005)
            resp = self.vxi.read()

        self._log(f"RX  {resp}")
        return resp

    def is_connected(self):
    
        return (
            (self.backend == "visa" and self.inst is not None)
            or
            (self.backend == "vxi11" and self.vxi is not None)
        )

##########################################################################
# MAIN WINDOW
##########################################################################

class HorizontalSeparator(QWidget):

    def __init__(self, text="", parent=None):
        super().__init__(parent)

        left = QFrame()
        left.setFrameShape(QFrame.HLine)
        left.setFrameShadow(QFrame.Sunken)

        right = QFrame()
        right.setFrameShape(QFrame.HLine)
        right.setFrameShadow(QFrame.Sunken)

        left.setFixedHeight(2)
        right.setFixedHeight(2)
        
        left.setStyleSheet("background-color: gray; border: none;")
        right.setStyleSheet("background-color: gray; border: none;")

        label = QLabel(text)
        label.setStyleSheet("""
            QLabel {
                font-weight: bold;
                padding-left: 8px;
                padding-right: 8px;
            }
        """)

        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 6, 0, 6)
        layout.setSpacing(5)

        layout.addWidget(left)
        layout.addWidget(label)
        layout.addWidget(right)

        layout.setStretch(0, 1)
        layout.setStretch(1, 0)
        layout.setStretch(2, 1)

class MainWindow(QMainWindow):

    CONFIG_FILE = "hp3458a_config.json"
    def __init__(self):

        super().__init__()
        
        self.setWindowTitle("xDevs.com HP3458A Diagnostic Utility")
        self.resize(1200, 900)
        self.load_config()

        self.dmm = HP3458A(self.log_message)
        self.log_buffer = []
        
        self.build_ui()
        self.restore_config()
        self.refresh_resources()
        self._session_header()
        self.faults = 0
        self.abort = 0

    def log_message(self, msg):

        line = f"{self.timestamp()}  {msg}"
        self.log_buffer.append(line)
        #self.log.appendPlainText(line)
        self.log.append(f'{line}')

        self.log.verticalScrollBar().setValue(
            self.log.verticalScrollBar().maximum()
        )

    def log_error(self, msg):

        line = f"{self.timestamp()}  {msg}"
        self.log_buffer.append(line)
        #self.log.appendPlainText(line)
        self.log.append(f'<span style="color:#f00;">{line}</span>')

        self.log.verticalScrollBar().setValue(
            self.log.verticalScrollBar().maximum()
        )

    def log_info(self, msg):

        line = f"{self.timestamp()}  {msg}"
        self.log_buffer.append(line)
        #self.log.appendPlainText(line)
        self.log.append(f'<span style="color:#00d;">{line}</span>')

        self.log.verticalScrollBar().setValue(
            self.log.verticalScrollBar().maximum()
        )

    def load_config(self):
    
        if not os.path.exists(self.CONFIG_FILE):
            return {}
    
        try:
            with open(self.CONFIG_FILE, "r") as f:
                return json.load(f)
    
        except Exception as e:
            self.log_message(f"CONFIG LOAD ERROR {e}")
            return {}
    
    def save_config(self):
    
        cfg = {
            "backend": self.backend_selector.currentText(),
            "visa_resource": self.resource.currentText(),
            "vxi11_ip": self.ip_input.text().strip(),
            "gpib_addr": self.gpib_input.text().strip(),
            "serial_number": self.sn_input.text().strip(),
            "user_note": self.user_note.text().strip()
        }
    
        try:
            with open(self.CONFIG_FILE, "w") as f:
                json.dump(cfg, f, indent=2)
    
            self.log_message("Config saved")
    
        except Exception as e:
            self.log_message(f"CONFIG SAVE ERROR {e}")
    
    def restore_config(self):
    
        cfg = self.load_config()
    
        self.backend_selector.setCurrentText(
            cfg.get("backend", "visa")
        )
    
        self.ip_input.setText(
            cfg.get("vxi11_ip", "")
        )
    
        self.gpib_input.setText(
            cfg.get("gpib_addr", "22")
        )
    
        sn = cfg.get("serial_number", "")
        self.sn_input.setText(sn)
        
        user_note = cfg.get("user_note", "")
        self.user_note.setText(user_note)
    
        self.serial_number = sn if sn else None
    
        visa = cfg.get("visa_resource", "")
        if visa:
            idx = self.resource.findText(visa)
            if idx >= 0:
                self.resource.setCurrentIndex(idx)
    
        self.log_message("Config restored")

    ######################################################################
    # UI
    ######################################################################
    def countdown_message_box(self, title, message, seconds):
    
        dlg = QDialog(self)
        dlg.setWindowTitle(title)
        dlg.setModal(True)
        dlg.resize(420, 200)
    
        layout = QVBoxLayout(dlg)
    
        label = QLabel(message)
        label.setWordWrap(True)
    
        timer_label = QLabel(f"Starting in {seconds} seconds...")
        timer_label.setStyleSheet("font-size: 14pt; font-weight: bold;")
    
        abort_btn = QPushButton("Exit")
        abort_btn.setStyleSheet("background-color: red; color: white; font-weight: bold;")
    
        layout.addWidget(label)
        layout.addWidget(timer_label)
        layout.addWidget(abort_btn)
    
        state = {
            "remaining": seconds,
            "aborted": False
        }
    
        def abort():
            state["aborted"] = True
            dlg.reject()
            self.abort = 1
        
        abort_btn.clicked.connect(abort)
    
        def tick():
    
            if state["aborted"]:
                return
    
            state["remaining"] -= 1
    
            if state["remaining"] <= 0:
                dlg.accept()
                timer.stop()
                return
    
            timer_label.setText(
                f"Executing in {state['remaining']} seconds... (Exit any time)"
            )
    
        timer = QTimer(dlg)
        timer.timeout.connect(tick)
        timer.start(1000)
    
        result = dlg.exec_()
    
        timer.stop()
        
        return not state["aborted"] and result == QDialog.Accepted

    def show_error(self, title, message, exception=None):
    
        # Write to log window
        self.log_message("=" * 60)
        self.log_message(f"ERROR: {title}")
        self.log_message(message)
    
        if exception is not None:
            tb = traceback.format_exc()
            self.log_message(tb)
    
        self.log_message("=" * 60)
    
        # Popup dialog

        msg = QMessageBox(self)
        msg.resize(900, 500)
        msg.setMinimumSize(900, 500)
        msg.setIcon(QMessageBox.Critical)
        msg.setWindowTitle(title)
        msg.setText(message)
        
        if exception is not None:
            msg.setDetailedText(traceback.format_exc())
    
        msg.setStandardButtons(QMessageBox.Ok)
        msg.exec_()

    def build_ui(self):

        central = QWidget()
        self.setCentralWidget(central)
        font = QFont("Consolas", 11)      # Font name, size
        font2 = QFont("Consolas", 13)      # Font name 2
        font3 = QFont("Consolas", 16)      # Font name 2
        
        layout = QVBoxLayout()
        central.setStyleSheet("background-color: #eeeeff;") 
        self.setStyleSheet("QMainWindow { background-color: white; }")
        
        # ---------------- VISA ----------------
        top = QHBoxLayout()

        top.addWidget(QLabel("Backend resource"))

        logo_label = QLabel(self)
        pixmap = QPixmap("header_logo.png")
        # 5. Set pixmap onto label and align it
        logo_label.setPixmap(pixmap)
        logo_label.setAlignment(Qt.AlignCenter)
        # 6. Add label to layout
        layout.addWidget(logo_label)

        self.info_label = QPlainTextEdit()
        self.info_label.setReadOnly(True)
        self.info_label.setPlainText(HELP_TEXT)
        self.info_label.setFixedHeight(390)
        self.info_label.setFont(font)
        layout.addWidget(self.info_label)

        self.resource = QComboBox()
        top.addWidget(self.resource)

        self.refresh_button = QPushButton("Refresh")
        self.refresh_button.clicked.connect(self.refresh_resources)
        top.addWidget(self.refresh_button)

        layout.addLayout(top)

        backend_row = QHBoxLayout()
        
        self.backend_selector = QComboBox()
        self.backend_selector.addItems(["VISA", "LXI/VXI"])
        
        self.ip_input = QLineEdit()
        self.ip_input.setPlaceholderText("LXI/VXI IP v4")
        
        self.gpib_input = QLineEdit()
        self.gpib_input.setPlaceholderText("GPIB addr (e.g. 22)")
        self.gpib_input.setText("22")
       
        backend_row.addWidget(QLabel("Backend: "))
        backend_row.addWidget(self.backend_selector)
        backend_row.addWidget(QLabel("TCP/IP v4: "))
        backend_row.addWidget(self.ip_input)
        backend_row.addWidget(QLabel("DMM GPIB: "))
        backend_row.addWidget(self.gpib_input)
        
        self.sn_input = QLineEdit()
        self.sn_input.setPlaceholderText("Instrument Serial Number (e.g. 1234567)")
        
        self.user_note = QLineEdit()
        self.user_note.setPlaceholderText("User note")
               
        layout.addLayout(backend_row)
        
        row_sn = QHBoxLayout()
        row_sn.addWidget(QLabel("DUT Serial No:"))
        row_sn.addWidget(self.sn_input)
        row_sn.addWidget(QLabel("User note:"))
        row_sn.addWidget(self.user_note)
        layout.addLayout(row_sn)

        # ---------------- CONNECTION ----------------
        self.is_connected = False # Flag
        
        row1 = QHBoxLayout()
        row1b = QHBoxLayout()

        self.connect_button = QPushButton("Connect")
        self.connect_button.setFont(font2)
        self.connect_button.setStyleSheet("height: 30px; background-color: #3f84e5; color: white; border-radius: 10px; border: 3px solid #000;")
        
        self.id_button = QPushButton("ID?")
        self.id_button.setFont(font2)
        self.id_button.setStyleSheet("height: 30px; background-color: #2e8abf; color: white; border-radius: 10px; border: 2px solid #000;")

        self.idn_button = QPushButton("*IDN?")
        self.idn_button.setFont(font2)
        self.idn_button.setStyleSheet("height: 30px; background-color: #2e8abf; color: white; border-radius: 10px; border: 2px solid #000;")

        row1.addWidget(self.connect_button)

        layout.addLayout(row1)
        
        self.footprint_button = QPushButton("Read footprint?")
        self.footprint_button.setFont(font2)
        self.footprint_button.setStyleSheet("height: 30px; background-color: #1f562c; color: #fe4; border-radius: 10px; border: 2px solid #000;")

        row1.addWidget(self.footprint_button)

        self.full_diag_button = QPushButton("PERFORM HEALTH CHECKS?")
        self.full_diag_button.setFont(font3)
        self.full_diag_button.setStyleSheet("height: 50px; color: #000011; background-color: #ffee00; border-radius: 20px; border: 4px solid #0055bb;")
        
        row1b.addWidget(self.full_diag_button)

        layout.addLayout(row1b)
        
        layout.addWidget(HorizontalSeparator("3458A Footprint Information Readback"))
        
        fr_row = QHBoxLayout()
        fr_row2 = QHBoxLayout()
        fr_row3 = QHBoxLayout()
        fr_row4 = QHBoxLayout()
        
        fr_row.addWidget(QLabel("Detected instrument"))
        self.fp1_notes = QLabel("---")
        fr_row.addWidget(self.fp1_notes)
        fr_row.addWidget(QLabel("Firmware (latest is 9,2)"))
        self.fp2_notes = QLabel("---")
        fr_row.addWidget(self.fp2_notes)
        fr_row.addWidget(QLabel("Options enabled"))
        self.fp3_notes = QLabel("---")
        fr_row.addWidget(self.fp3_notes)
        fr_row.addWidget(QLabel("TEMP?"))
        self.fp4_notes = QLabel("---")
        fr_row.addWidget(self.fp4_notes)
        fr_row.addWidget(QLabel("Errors?"))
        self.fp5_notes = QLabel("---")
        fr_row.addWidget(self.fp5_notes)
        
        fr_row2.addWidget(QLabel("CALSTR?"))
        self.fp6_notes = QLabel("---")
        fr_row2.addWidget(self.fp6_notes)
        
        fr_row3.addWidget(QLabel("Overloads?"))
        self.fp7_notes = QLabel("---")
        fr_row3.addWidget(self.fp7_notes)
        
        fr_row4.addWidget(QLabel("LTZ1000 Voltage"))
        self.fp8_notes = QLabel("---")
        fr_row4.addWidget(self.fp8_notes)
        
        fr_row4.addWidget(QLabel("VHP101 Resistance"))
        self.fp9_notes = QLabel("---")
        fr_row4.addWidget(self.fp9_notes)
        
        fr_row4.addWidget(QLabel("10V DC gain (CAL72)"))
        self.fp10_notes = QLabel("---")
        fr_row4.addWidget(self.fp10_notes)
        
        fr_row4.addWidget(QLabel("Faults detected"))
        self.fp11_notes = QLabel("---")
        fr_row4.addWidget(self.fp11_notes)
        
        self.fp1_notes.setFont(font2)
        self.fp2_notes.setFont(font2)
        self.fp3_notes.setFont(font2)
        self.fp4_notes.setFont(font2)
        self.fp5_notes.setFont(font2)
        self.fp6_notes.setFont(font2)
        self.fp7_notes.setFont(font2)
        self.fp8_notes.setFont(font2)
        self.fp9_notes.setFont(font2)
        self.fp10_notes.setFont(font2)
        
        layout.addLayout(fr_row)
        layout.addLayout(fr_row2)
        layout.addLayout(fr_row3)
        layout.addLayout(fr_row4)
        
        row2 = QHBoxLayout()

        row2.addWidget(self.id_button)
        row2.addWidget(self.idn_button)

        self.err_button = QPushButton("ERRSTR?")
        self.err_button.setFont(font2)
        self.err_button.setStyleSheet("height: 30px; background-color: #e7c69a; color: #006; border-radius: 5px; border: 1px solid #000;")
        self.reset_button = QPushButton("RESET")
        self.reset_button.setFont(font2)
        self.reset_button.setStyleSheet("height: 30px; background-color: #f8f3f4; color: #006; border-radius: 5px; border: 1px solid #000;")
        self.preset_button = QPushButton("PRESET NORM")
        self.preset_button.setFont(font2)
        self.preset_button.setStyleSheet("height: 30px; background-color: #f8f3f4; color: #006; border-radius: 5px; border: 1px solid #000;")
                
        row3 = QHBoxLayout()
        row4 = QHBoxLayout()
        
        self.test_button = QPushButton("RUN SELF-TEST DIAG")
        self.test_button.setFont(font2)
        self.test_button.setStyleSheet("height: 30px; background-color: #bbddee; color: #006; border-radius: 5px; border: 1px solid #000;")
        self.acal1_button = QPushButton("ACAL DCV")
        self.acal1_button.setFont(font2)
        self.acal1_button.setStyleSheet("height: 30px; background-color: #f1d7c7; color: #006; border-radius: 5px; border: 1px solid #b13;")
        self.acal2_button = QPushButton("ACAL OHMS")
        self.acal2_button.setFont(font2)
        self.acal2_button.setStyleSheet("height: 30px; background-color: #f1d7c7; color: #006; border-radius: 5px; border: 1px solid #b13;")
        self.acal3_button = QPushButton("ACAL AC")
        self.acal3_button.setFont(font2)
        self.acal3_button.setStyleSheet("height: 30px; background-color: #f1d7c7; color: #006; border-radius: 5px; border: 1px solid #b13;")
        self.acal4_button = QPushButton("ACAL ALL")
        self.acal4_button.setFont(font2)
        self.acal4_button.setStyleSheet("height: 30px; background-color: #f1d7c7; color: #006; border-radius: 5px; border: 1px solid #b13;")
        self.opt_button = QPushButton("Options?")
        self.opt_button.setFont(font2)
        self.opt_button.setStyleSheet("height: 30px; background-color: #d7bcd6; color: #050; border-radius: 5px; border: 1px solid #000;")
        self.rev_button = QPushButton("Revision?")
        self.rev_button.setFont(font2)
        self.rev_button.setStyleSheet("height: 30px; background-color: #d7bcd6; color: #050; border-radius: 5px; border: 1px solid #000;")
        self.sync_button = QPushButton("Set ACV Sync")
        self.sync_button.setFont(font2)
        self.sync_button.setStyleSheet("height: 30px; background-color: #d7bcd6; color: #050; border-radius: 5px; border: 1px solid #000;")
        self.cal_button = QPushButton("DUMP CAL VALUES")
        self.cal_button.setFont(font2)
        self.cal_button.setStyleSheet("height: 30px; background-color: #a6ee00; color: #050; border-radius: 5px; border: 1px solid #000;")
        self.calstr_button = QPushButton("Read CALSTR?")
        self.calstr_button.setFont(font2)
        self.calstr_button.setStyleSheet("height: 30px; background-color: #a6ee00; color: #050; border-radius: 5px; border: 1px solid #000;")
        
        row2.addWidget(self.opt_button)
        row2.addWidget(self.rev_button)
        row2.addWidget(self.reset_button)
        row2.addWidget(self.preset_button)
        row2.addWidget(self.sync_button)
        
        row3.addWidget(self.test_button)
        row3.addWidget(self.acal1_button)
        row3.addWidget(self.acal2_button)
        row3.addWidget(self.acal3_button)
        row3.addWidget(self.acal4_button)
        
        row4.addWidget(self.err_button)
        row4.addWidget(self.cal_button)
        row4.addWidget(self.calstr_button)
        

        # ---------------- MANUAL COMMAND ----------------
        cmd_row = QHBoxLayout()

        self.cmd_input = QLineEdit()
        self.cmd_input.setPlaceholderText("Enter HP3458A command (e.g. DCV 10, ERRSTR?, NPLC 100)")

        self.send_button = QPushButton("QUERY")

        cmd_row.addWidget(self.cmd_input)
        cmd_row.addWidget(self.send_button)


        # ---------------- LOG ----------------
        self.log = QTextEdit()
        self.log.setReadOnly(True)
        self.log.setFixedHeight(300)
        self.log.setFont(font)
        layout.addWidget(self.log)
        
        # ---------------- USER NOTES ----------------
        
        # Create the horizontal line
        layout.addWidget(HorizontalSeparator("Diagnostics"))
        layout.addLayout(cmd_row)
        layout.addLayout(row2)
        
        layout.addWidget(HorizontalSeparator("Advanced functionality"))
        layout.addLayout(row3)
        layout.addLayout(row4)               
        
        central.setLayout(layout)
        
        # ---------------- STATUS ----------------
        self.status = QLabel("Disconnected")
        self.status.setStyleSheet("color:red;font-weight:bold;")
        layout.addWidget(self.status)

        
        # ---------------- SIGNALS ----------------
        #self.connect_button.clicked.connect(self.connect_meter)
        #self.disconnect_button.clicked.connect(self.disconnect_meter)
        self.connect_button.clicked.connect(self.toggle_connection)
        
        self.footprint_button.clicked.connect(self.dump_footprint)
        
        self.id_button.clicked.connect(self.read_id)
        self.idn_button.clicked.connect(self.read_idn)

        self.err_button.clicked.connect(self.read_err)
        self.reset_button.clicked.connect(self.reset_inst)
        self.preset_button.clicked.connect(self.preset_inst)

        self.acal1_button.clicked.connect(self.acal1_inst)
        self.acal2_button.clicked.connect(self.acal2_inst)
        self.acal3_button.clicked.connect(self.acal3_inst)
        self.acal4_button.clicked.connect(self.acal4_inst)
        self.rev_button.clicked.connect(self.rev_inst)
        self.opt_button.clicked.connect(self.opt_inst)
        self.test_button.clicked.connect(self.test_inst)
        self.sync_button.clicked.connect(self.sync_inst)
        self.calstr_button.clicked.connect(self.calstr_inst)
        self.cal_button.clicked.connect(self.dump_cal_constants)
        
        self.send_button.clicked.connect(self.send_command)
        self.full_diag_button.clicked.connect(self.perform_diags)

    ######################################################################
    # LOGGING
    ######################################################################

    def timestamp(self):
        return datetime.datetime.now().strftime("%H:%M:%S")

    def _session_header(self):

        self.log_message("=" * 60)
        self.log_message("HP3458A Diagnostic Session")
        self.log_info(f"Start: {datetime.datetime.now()}")
        self.log_info(f"Backend: {self.dmm.backend}")
        self.log_info(f"Serial: {self.sn_input.text().strip() or 'NOT SET'}")
        self.log_info(f"User note: {self.user_note.text().strip() or 'NOT SET'}")
        self.log_message("=" * 60)

    def require_conn(self):

        if not self.dmm or not self.dmm.backend:
            QMessageBox.warning(self, "Not connected backend", "Connect first")
            return False
    
        if not self.dmm.is_connected():
            QMessageBox.warning(self, "Not connected DMM", "Connect first")
            return False
    
        return True
        
    def auto_save_log(self):

        if not self.log_buffer:
            return

        try:
            filename = (
                f"HP3458A_autosave_"
                f"{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
            )
    
            with open(filename, "w", encoding="utf-8") as f:
                f.write("\n".join(self.log_buffer))
    
            # optional console feedback (not UI notify to avoid shutdown issues)
            print(f"[AUTO SAVE] Log saved to {filename}")

        except Exception as e:
            print(f"[AUTO SAVE ERROR] {e}")

    def closeEvent(self, event):
    
        try:
            self.log_info("Application closing...")
    
            # auto-save log BEFORE shutdown
            self.auto_save_log()
            self.save_config()    
            
            # safely close instrument
            self.dmm.close()
    
        except Exception as e:
            print(f"Close error: {e}")
    
        event.accept()

    ######################################################################
    # VISA
    ######################################################################

    def refresh_resources(self):

        self.resource.clear()
        try:
            rm = pyvisa.ResourceManager()
            for r in rm.list_resources():
                self.resource.addItem(r)
            rm.close()
        
            self.log_message("VISA refreshed")
        
        except Exception as e:
            self.log_error(f"ERROR {e}")
            
            
    def connect_meter(self):
        try:
            mode = self.backend_selector.currentText()
            if mode == "VISA":
                addr = self.resource.currentText()
                self.dmm.open_visa(addr)
                self.status.setText("Connected (VISA)")
            else:
                ip = self.ip_input.text().strip()
                gpib = self.gpib_input.text().strip()
                if not ip or not gpib:
                    QMessageBox.warning(self, "Missing", "IP and GPIB required")
                    return
                self.dmm.open_vxi11(ip, gpib)
                self.status.setText("Connected (VXI11)")
    
            self.status.setStyleSheet("color:green;font-weight:bold;")
            self.is_connected = True
            self.update_connection_ui()
    
            self.log_message("Connected OK")
            self.serial_number = self.sn_input.text().strip() or "UNKNOWN"
            self.log_message(f"SN = {self.serial_number}")
            self.save_config()
            self.fp1_notes.setText("????")
            self.fp2_notes.setText("????")
            self.fp3_notes.setText("????")
            self.fp4_notes.setText("????")
            self.fp5_notes.setText("????")
            self.fp6_notes.setText("????")
            self.fp7_notes.setText("????")
            self.fp8_notes.setText("????")
            self.fp9_notes.setText("????")
            self.fp10_notes.setText("????")
            self.fp11_notes.setText("?")
            
            self.dmm.write("TARM HOLD")
            self.dmm.write("TRIG SGL")
            self.dmm.write("PRESET NORM")
            self.dmm.write("OFORMAT ASCII")
            self.dmm.write("FUNC DCV,AUTO")
            self.dmm.write("NPLC 0.001")
            self.dmm.write("AZERO ON")
            self.dmm.write("NRDGS 1,AUTO")
            self.dmm.write("MEM OFF")
            self.dmm.write("END ALWAYS")
            self.dmm.write("NDIG 9")
            
        except Exception as e:
            self.show_error("Connection Error", str(e), e)
            self.log_error(f"ERROR {e}")
    
    def disconnect_meter(self):
    
        self.dmm.write("RESET")
        self.dmm.close()
        self.abort = 0
        self.is_connected = False
        self.update_connection_ui()
        self.status.setText("Disconnected")
        self.status.setStyleSheet("color:red;font-weight:bold;")
        self.fp1_notes.setText("----")
        self.fp2_notes.setText("----")
        self.fp3_notes.setText("----")
        self.fp4_notes.setText("----")
        self.fp5_notes.setText("----")
        self.fp6_notes.setText("----")
        self.fp7_notes.setText("----")
        self.fp8_notes.setText("----")
        self.fp9_notes.setText("----")
        self.fp10_notes.setText("----")
        self.fp11_notes.setText("----")
        self.log_info("Disconnected")

    def toggle_connection(self):
    
        if not self.is_connected:
            self.connect_meter()
        else:
            self.disconnect_meter()

    def update_connection_ui(self):
    
        if self.is_connected:
            self.connect_button.setText("DISCONNECT")
            self.connect_button.setStyleSheet("height: 30px; background-color: #3f784c; color: white; border-radius: 4px; border: 4px solid #000;")
            self.status.setText("Connected")
            self.status.setStyleSheet("color:green;font-weight:bold;")
    
        else:
            self.connect_button.setText("CONNECT")
            self.connect_button.setStyleSheet("height: 30px; background-color: #3f84e5; color: white; border-radius: 4px; border: 4px solid #000;")
            self.status.setText("Disconnected")
            self.status.setStyleSheet("color:red;font-weight:bold;")

    ######################################################################
    # BASIC COMMANDS
    ######################################################################

    def read_id(self):

        if not self.require_conn():
            return

        try:
            print ("Trying ID?")
            resp = self.dmm.query("ID?")
            self.log_message(f"ID = {resp.strip()}")
            self.fp1_notes.setText("%s" % resp.strip())
            self.fp1_notes.setStyleSheet("color: #080; font-weight: bold;")
            return (f"{resp.strip()}")
        except Exception as e:
            self.log_error(f"ERROR {e}")
            self.show_error(
                "ID Error",
                str(e),
                e
            )

    def read_idn(self):

        if not self.require_conn():
            return

        try:
            resp = self.dmm.query("*IDN?")
            self.log_message(f"*IDN? = {resp.strip()}")
            self.fp1_notes.setText("%s" % resp.strip())
            self.fp1_notes.setStyleSheet("color: #f00; font-weight: bold;")
            return (f"{resp.strip()}")
        except Exception as e:
            self.log_error(f"ERROR {e}")
            self.show_error(
                "IDN Error",
                str(e),
                e
            )

    ######################################################################
    # SERVICE COMMANDS
    ######################################################################

    def read_err(self):

        if not self.require_conn():
            return

        try:
            resp = self.dmm.query("ERRSTR?")
            if (resp.strip()) != '0,"NO ERROR"':
                self.log_message(f"ERRSTR = {resp.strip()}")
                self.faults = self.faults + 1
            self.fp11_notes.setText("%d" % self.faults)
            self.fp11_notes.setStyleSheet("color:#000;font-size: 14pt; font-weight:bold;")
            return (f"{resp.strip()}")
        except Exception as e:
            self.log_error(f"ERROR {e}")
            #self.show_error("Read Error",str(e), e )

    def reset_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("RESET")
        self.dmm.write("TARM HOLD")
        self.dmm.write("TRIG SGL")
        self.dmm.write("PRESET NORM")
        self.dmm.write("OFORMAT ASCII")
        self.dmm.write("FUNC DCV,AUTO")
        self.dmm.write("NPLC 0.001")
        self.dmm.write("AZERO ON")
        self.dmm.write("NRDGS 1,AUTO")
        self.dmm.write("MEM OFF")
        self.dmm.write("END ALWAYS")
        self.dmm.write("NDIG 9")
        self.log_message("RESET sent")

    def preset_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("PRESET NORM")
        self.log_message("PRESET NORM sent")

    def acal1_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("ACAL DCV")
        self.log_message("ACAL DCV sent")
        self.countdown_message_box("ACAL DCV PROCESS", "Running artifact self-calibration\r DC voltage, 143 seconds", 143)
        self.log_message("ACAL DCV done")

    def acal2_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("ACAL OHMS")
        self.log_message("ACAL OHMS sent")
        self.countdown_message_box("ACAL OHMS PROCESS", "Running artifact self-calibration\r OHMS, 600 seconds", 600)
        self.log_message("ACAL OHMS done")
        
    def acal3_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("ACAL AC")
        self.log_message("ACAL AC sent")
        self.countdown_message_box("ACAL AC PROCESS", "Running artifact self-calibration\r AC, 143 seconds", 143)
        self.log_message("ACAL AC done")
        
    def acal4_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("ACAL ALL")
        self.log_message("ACAL ALL sent")
        self.countdown_message_box("ACAL ALL PROCESS", "Running artifact self-calibration\r ALL, 860 seconds", 860)
        self.log_message("ACAL ALL done")

    def opt_inst(self):

        if not self.require_conn():
            return

        strg = self.dmm.query("OPT?")
        self.log_message("Options: %s" % strg.strip())
        self.fp3_notes.setText("%s" % strg.strip())            
        
    def rev_inst(self):

        if not self.require_conn():
            return
        strg = self.dmm.query("REV?")
        self.log_message("Firmware version: %s" % strg.strip())
        self.fp2_notes.setText("%s" % strg.strip())

    def test_inst(self):

        if not self.require_conn():
            return
        print ("Test started")
        self.dmm.write("TEST")
        self.log_message("TEST started")
        self.countdown_message_box("SELF_TEST PROCESS", "Running self-test", 80)
        #time.sleep(80)
        self.log_message("TEST time finished")
        self.read_err()
        self.read_err()
        self.read_err()
        self.read_err()
        print ("Test finished")
        self.log_message("TEST Done")
        
    def perform_diags(self):

        if not self.require_conn():
            return

        self.log_message(f"Started diagnostics...")
        try:
            rxdmm = self.read_id()
            self.log_message(f"ID = {rxdmm}")
            print (rxdmm)
            
            print ("Checking meter....")
            self.log_message("Checking meter...")
            self.dump_footprint()

            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
                        
            print ("Testing....")
            self.log_message("Testing...")
            if (self.abort == 0):
                self.test_inst()
            else:
                self.log_message(f"Diag test skipped...")
            
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            
            if (self.abort == 0):
                print ("Starting ACAL DCV....")
                self.acal1_inst()
            else:
                self.log_message(f"Diag ACAL DCV skipped...")

            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            
            if (self.abort == 0):
                print ("Starting ACAL OHM....")
                self.acal2_inst()
            else:
                self.log_message(f"Diag ACAL OHM skipped...")
            
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            
            if (self.abort == 0):
                print ("Starting ACAL AC....")
                self.acal3_inst()
            else:
                self.log_message(f"Diag ACAL AC skipped...")
                
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()
            self.read_err()

            if (self.abort == 0):
                print ("Dumping constants....")
                self.log_info("Dumping constants...")
                self.dump_cal_constants()
            self.log_message(f"Total faults : {self.faults}")

        except Exception as e:
            self.log_message(f"Diagnostics errored out...")


    def sync_inst(self):

        if not self.require_conn():
            return

        self.dmm.write("ACV 1000")
        self.dmm.write("SETACV SYNC")
        self.log_message("ACV configured to syncronous")
    
    def calstr_inst(self):
        if not self.require_conn():
            return

        strgb = self.dmm.query("CALSTR?")
        self.log_message("Calibration string = %s" % strgb)
    
    def dump_cal_constants(self):

        if not self.require_conn():
            return
    
        try:
            self.log_message("TX  CAL?")
            cal_data = []
            cix = 0
            print ("Start constants readout %d" % cix)
           
            while cix <= 253:
                ccvalue = self.dmm.query("CAL? %d,1" % cix)
                #print ("Constant %d: %s" % (cix, ccvalue.strip()))
                #self.log_message("CC[%d]: %s" % (cix, ccvalue.strip()))
                cal_data.append("%d:%s" % (cix, ccvalue.strip()))
                ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
                cix = cix + 1
    
            filename = (
                f"HP3458A_CAL_"
                f"GPIB{self.gpib_input.text().strip()}_"
                f"SN{self.serial_number}_"
                f"{ts}.txt"
            )
    
            with open(filename, "w", encoding="utf-8") as f:
    
                f.write("HP3458A CAL CONSTANT DUMP\n")
                f.write("=" * 60 + "\n")
                f.write(f"SN: {self.serial_number}\n")
                f.write(f"Time: {ts}\n")
                f.write(f"Backend: {self.dmm.backend}\n")
                f.write("\n")
                print (cal_data)
                cix = 0
                while cix <= 253:
                    f.write("\r%s" % cal_data[cix])
                    #print("%s" % cal_data[cix])
                    cix = cix + 1
    
            self.log_message(f"CAL saved → {filename}")
            print ("Finished constants readout")
        except Exception as e:
            self.log_error(f"CALDUMP ERROR {e}")
            self.show_error(
                "Constants readout error",
                str(e),
                e
            )

            
    def dump_footprint(self):

        if not self.require_conn():
            return
    
        try:
            self.log_message("Initialize meter?")
            self.dmm.write("RESET")
            self.dmm.write("PRESET NORM")
            self.dmm.write("END ALWAYS")
            self.dmm.write("TRIG AUTO")
            self.log_message("FOOTPRINT?")
            
            rx_data = self.dmm.query("OPT?")
            self.log_message("Meter options received %s" % rx_data)
            self.fp3_notes.setText("%s" % rx_data.strip())
            self.fp3_notes.setStyleSheet("color:#050;font-weight:bold;")
            
            rx_data = self.dmm.query("REV?")
            self.log_message("Meter revision received %s" % rx_data)
            self.fp2_notes.setText("%s" % rx_data.strip())
            self.fp2_notes.setStyleSheet("color:#050;font-weight:bold;")
            
            rx_data = self.dmm.query("TEMP?")
            self.log_message("A1 PCBA temperature received %s" % rx_data)
            self.fp4_notes.setText("%s" % rx_data.strip())
            self.fp4_notes.setStyleSheet("color:#050;font-weight:bold;")
            
            rx_data = self.dmm.query("ERRSTR?")
            self.log_message("Error string received %s" % rx_data)
            self.fp5_notes.setText("%s" % rx_data.strip())
            self.fp5_notes.setStyleSheet("color:#050;font-weight:bold;")
            
            rx_data = self.dmm.query("ID?")
            self.log_message("Meter ID received %s" % rx_data)
            self.fp1_notes.setText("%s" % rx_data.strip())
            self.fp1_notes.setStyleSheet("color:#050;font-weight:bold;")
                        
            rx_data = self.dmm.query("CALSTR?")
            self.log_message("CALSTR? received %s" % rx_data)
            self.fp6_notes.setText("%s" % rx_data.strip())
            self.fp6_notes.setStyleSheet("color:#050;font-weight:bold;")
            
            rx_data = self.dmm.query("CAL? 2941")
            self.log_message("Overloads received %s" % rx_data)
            self.fp7_notes.setText("%s" % rx_data.strip())
            self.fp7_notes.setStyleSheet("color:#050;font-weight:bold;")
            
            rx_data = self.dmm.query("CAL? 2,1")
            self.log_message("A9 Zener received %s" % rx_data)
            self.fp8_notes.setText("%s" % rx_data.strip())
            self.fp8_notes.setStyleSheet("color:#01a;font-weight:bold;")
            
            rx_data = self.dmm.query("CAL? 1,1")
            self.log_message("Resistors received %s" % rx_data)
            self.fp9_notes.setText("%s" % rx_data.strip())
            self.fp9_notes.setStyleSheet("color:#01a;font-weight:bold;")
            
            rx_data = self.dmm.query("CAL? 72")
            self.log_message("10V gain received %s" % rx_data)
            self.fp10_notes.setText("%s" % rx_data.strip())
            self.fp10_notes.setStyleSheet("color:#01a;font-weight:bold;")
            
            print ("Footprinting done")
            
            
        except Exception as e:
            self.log_error(f"Footprinting Error: {e}")
    
    ######################################################################
    # MANUAL COMMAND
    ######################################################################

    def send_command(self):

        if not self.require_conn():
            return

        cmd = self.cmd_input.text().strip()

        if not cmd:
            return

        try:
            if "?" in cmd:
                resp = self.dmm.query(cmd)
                self.log_message(f"{cmd} = {resp.strip()}")
            else:
                self.dmm.write(cmd)
                self.log_message(f"SENT {cmd}")

        except Exception as e:
            self.log_error(f"ERROR {e}")


##########################################################################
# MAIN
##########################################################################

def main():

    app = QApplication(sys.argv)
    win = MainWindow()
    win.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()